using Nala.Core.Email;
using Nala.Core.Users;

namespace Nala.Core.Auth;

public abstract record CreateResetLinkResult
{
    public sealed record Created(string Token, DateTimeOffset ExpiresAt) : CreateResetLinkResult;

    public sealed record Forbidden : CreateResetLinkResult;

    /// <summary>Unknown or deleted user.</summary>
    public sealed record NotFound : CreateResetLinkResult;

    public sealed record AccountDisabled : CreateResetLinkResult;
}

public abstract record ResetLinkLookup
{
    public sealed record Valid(string Email, DateTimeOffset ExpiresAt) : ResetLinkLookup;

    public sealed record Unavailable(ResetLinkProblem Problem) : ResetLinkLookup;

    public sealed record AccountDisabled : ResetLinkLookup;
}

public abstract record RequestResetResult
{
    /// <summary>The same answer whether or not an email was sent.</summary>
    public sealed record Requested : RequestResetResult;

    /// <summary>Field name → error code (<c>email</c>: <c>required</c>, <c>invalid</c>).</summary>
    public sealed record Invalid(IReadOnlyDictionary<string, string> Errors) : RequestResetResult;
}

public sealed record ResetPasswordCommand(string? Token, string? Password);

public abstract record ResetPasswordResult
{
    public sealed record Reset(User User) : ResetPasswordResult;

    public sealed record Unavailable(ResetLinkProblem Problem) : ResetPasswordResult;

    public sealed record AccountDisabled : ResetPasswordResult;

    /// <summary>Field name → error code (<c>password</c>: <c>required</c>, <c>tooShort</c>).</summary>
    public sealed record Invalid(IReadOnlyDictionary<string, string> Errors) : ResetPasswordResult;
}

/// <summary>One-time links that set a new password: generated by the admin, used by anyone holding them.</summary>
public class PasswordResetService(
    IPasswordResetTokenRepository resets,
    IUserRepository users,
    ISessionRepository sessions,
    ILoginFailureRepository loginFailures,
    IPasswordHasher hasher,
    IEmailOutbox outbox,
    TimeProvider time)
{
    /// <summary>Admin only. Replaces the user's earlier unused links.</summary>
    public async Task<CreateResetLinkResult> CreateLinkAsync(
        User actor, Guid userId, CancellationToken cancellationToken = default)
    {
        if (!actor.IsAdmin)
        {
            return new CreateResetLinkResult.Forbidden();
        }

        var user = await users.GetByIdAsync(userId, cancellationToken);
        if (user is not { DeletedAt: null })
        {
            return new CreateResetLinkResult.NotFound();
        }

        if (user.IsDisabled)
        {
            return new CreateResetLinkResult.AccountDisabled();
        }

        var token = LinkToken.Generate();
        var now = time.GetUtcNow();
        var reset = new PasswordResetToken
        {
            Id = Guid.NewGuid(),
            TokenHash = LinkToken.Hash(token),
            UserId = user.Id,
            CreatedAt = now,
            ExpiresAt = now + PasswordResetPolicy.AdminLinkLifetime,
        };
        await resets.ReplaceAsync(reset, cancellationToken);
        return new CreateResetLinkResult.Created(token, reset.ExpiresAt);
    }

    /// <summary>"Forgot password": emails a link to an active account, at most once per interval. The result never tells whether one was sent.</summary>
    public async Task<RequestResetResult> RequestByEmailAsync(
        string? email, Uri publicUrl, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(email))
        {
            return new RequestResetResult.Invalid(new Dictionary<string, string> { ["email"] = "required" });
        }

        if (!EmailAddress.TryNormalize(email, out var normalized))
        {
            return new RequestResetResult.Invalid(new Dictionary<string, string> { ["email"] = "invalid" });
        }

        var user = await users.GetByEmailAsync(normalized, cancellationToken);
        if (user is not { DeletedAt: null, IsDisabled: false })
        {
            return new RequestResetResult.Requested();
        }

        var now = time.GetUtcNow();
        if (await resets.LatestCreatedAtAsync(user.Id, cancellationToken) is { } latest
            && now - latest < PasswordResetPolicy.EmailInterval)
        {
            return new RequestResetResult.Requested();
        }

        var token = LinkToken.Generate();
        await resets.ReplaceAsync(
            new PasswordResetToken
            {
                Id = Guid.NewGuid(),
                TokenHash = LinkToken.Hash(token),
                UserId = user.Id,
                CreatedAt = now,
                ExpiresAt = now + PasswordResetPolicy.EmailLinkLifetime,
            },
            cancellationToken);
        outbox.Enqueue(PasswordResetEmail.Compose(user, publicUrl, token));
        return new RequestResetResult.Requested();
    }

    public async Task<ResetLinkLookup> LookupAsync(string? token, CancellationToken cancellationToken = default)
    {
        var (reset, user, refusal) = await FindUsableAsync(token, cancellationToken);
        return refusal ?? new ResetLinkLookup.Valid(user!.Email!, reset!.ExpiresAt);
    }

    /// <summary>
    /// The link is checked before the password. Sets the new password, consumes the link, ends every session of the user
    /// and clears their login failures; the caller then signs them in.
    /// </summary>
    public async Task<ResetPasswordResult> ResetAsync(ResetPasswordCommand command, CancellationToken cancellationToken = default)
    {
        var (reset, user, refusal) = await FindUsableAsync(command.Token, cancellationToken);
        switch (refusal)
        {
            case ResetLinkLookup.AccountDisabled:
                return new ResetPasswordResult.AccountDisabled();
            case ResetLinkLookup.Unavailable unavailable:
                return new ResetPasswordResult.Unavailable(unavailable.Problem);
        }

        if (string.IsNullOrEmpty(command.Password))
        {
            return new ResetPasswordResult.Invalid(new Dictionary<string, string> { ["password"] = "required" });
        }

        if (!PasswordPolicy.IsValid(command.Password))
        {
            return new ResetPasswordResult.Invalid(new Dictionary<string, string> { ["password"] = "tooShort" });
        }

        // Another reset may have used the link since it was read.
        if (!await resets.ConsumeAsync(reset!.Id, time.GetUtcNow(), cancellationToken))
        {
            return new ResetPasswordResult.Unavailable(ResetLinkProblem.Used);
        }

        user!.PasswordHash = hasher.Hash(command.Password);
        await users.UpdateAsync(user, cancellationToken);
        await sessions.DeleteAllAsync(user.Id, cancellationToken);
        await loginFailures.ClearAsync(user.Email!, cancellationToken);
        return new ResetPasswordResult.Reset(user);
    }

    /// <summary>The link and its user when usable; otherwise why not. A deleted user's link is unknown.</summary>
    private async Task<(PasswordResetToken? Reset, User? User, ResetLinkLookup? Refusal)> FindUsableAsync(
        string? token, CancellationToken cancellationToken)
    {
        var reset = string.IsNullOrEmpty(token)
            ? null
            : await resets.GetByTokenHashAsync(LinkToken.Hash(token), cancellationToken);
        var user = reset is null ? null : await users.GetByIdAsync(reset.UserId, cancellationToken);
        if (reset is null || user is not { DeletedAt: null })
        {
            return (null, null, new ResetLinkLookup.Unavailable(ResetLinkProblem.Unknown));
        }

        if (reset.ProblemAt(time.GetUtcNow()) is { } problem)
        {
            return (null, null, new ResetLinkLookup.Unavailable(problem));
        }

        return user.IsDisabled ? (null, null, new ResetLinkLookup.AccountDisabled()) : (reset, user, null);
    }
}
