using Nala.Api.Auth;
using Nala.Api.Entries;
using Nala.Core.Diapers;

namespace Nala.Api.Diapers;

/// <summary>
/// A new diaper, with its id generated by the client. Missing toggles are off (neither wet nor dirty is dry); colour and
/// consistency are ignored unless dirty.
/// </summary>
public sealed record CreateDiaperRequest(
    Guid? Id, Guid? BabyId, DateTimeOffset? Time, bool? Wet, bool? Dirty, bool? Rash, string? Color, string? Consistency, string? Notes);

/// <summary>Replaces every field; the baby can't change.</summary>
public sealed record UpdateDiaperRequest(
    DateTimeOffset? Time, bool? Wet, bool? Dirty, bool? Rash, string? Color, string? Consistency, string? Notes);

public sealed record DiaperResponse(
    Guid Id,
    Guid BabyId,
    DateTimeOffset Time,
    bool Wet,
    bool Dirty,
    bool Rash,
    string? Color,
    string? Consistency,
    string? Notes,
    UserNameResponse LoggedBy,
    UserNameResponse UpdatedBy,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

/// <summary>Newest first; <c>Next</c> is the cursor of the following page, null after the last one.</summary>
public sealed record DiaperPageResponse(IEnumerable<DiaperResponse> Entries, string? Next);

/// <summary>A baby's diapers (spec 07). Every member of the baby's family may add, edit and delete any diaper (fallback session policy, family check in Core).</summary>
public static class DiaperEndpoints
{
    public static IServiceCollection AddNalaDiapers(this IServiceCollection services) =>
        services.AddScoped<DiaperService>();

    public static IEndpointRouteBuilder MapNalaDiapers(this IEndpointRouteBuilder endpoints)
    {
        var diapers = endpoints.MapGroup("/api/diapers");
        diapers.MapPost("", CreateAsync);
        diapers.MapGet("/{id:guid}", GetAsync);
        diapers.MapPut("/{id:guid}", UpdateAsync);
        diapers.MapDelete("/{id:guid}", DeleteAsync);

        endpoints.MapGet("/api/babies/{babyId:guid}/diapers", ListAsync);
        return endpoints;
    }

    /// <summary>201 for a new diaper; 200 with the stored diaper when its id exists already (a re-sent request).</summary>
    private static async Task<IResult> CreateAsync(
        CreateDiaperRequest request, DiaperService diapers, HttpContext context, CancellationToken cancellationToken)
    {
        var missing = new Dictionary<string, string>();
        if (request.Id is null)
        {
            missing["id"] = "required";
        }

        if (request.BabyId is null)
        {
            missing["babyId"] = "required";
        }

        if (missing.Count > 0)
        {
            return AuthEndpoints.ValidationProblem(missing);
        }

        var input = Input(request.Time, request.Wet, request.Dirty, request.Rash, request.Color, request.Consistency, request.Notes);
        return await diapers.CreateAsync(AuthEndpoints.CurrentUser(context)!, request.Id!.Value, request.BabyId!.Value, input, cancellationToken) switch
        {
            CreateDiaperResult.Created created => Results.Created($"/api/diapers/{created.Entry.Diaper.Id}", ToResponse(created.Entry)),
            CreateDiaperResult.AlreadyExists existing => Results.Ok(ToResponse(existing.Entry)),
            CreateDiaperResult.NotFound => DiaperNotFound(),
            CreateDiaperResult.Invalid invalid => AuthEndpoints.ValidationProblem(invalid.Errors),
            _ => BabyNotFound(),
        };
    }

    private static async Task<IResult> GetAsync(Guid id, DiaperService diapers, HttpContext context, CancellationToken cancellationToken) =>
        await diapers.GetAsync(AuthEndpoints.CurrentUser(context)!, id, cancellationToken) is { } entry ? Results.Ok(ToResponse(entry)) : DiaperNotFound();

    private static async Task<IResult> UpdateAsync(
        Guid id, UpdateDiaperRequest request, DiaperService diapers, HttpContext context, CancellationToken cancellationToken) =>
        await diapers.UpdateAsync(
                AuthEndpoints.CurrentUser(context)!,
                id,
                Input(request.Time, request.Wet, request.Dirty, request.Rash, request.Color, request.Consistency, request.Notes),
                cancellationToken) switch
        {
            UpdateDiaperResult.Updated updated => Results.Ok(ToResponse(updated.Entry)),
            UpdateDiaperResult.Invalid invalid => AuthEndpoints.ValidationProblem(invalid.Errors),
            _ => DiaperNotFound(),
        };

    private static async Task<IResult> DeleteAsync(Guid id, DiaperService diapers, HttpContext context, CancellationToken cancellationToken) =>
        await diapers.DeleteAsync(AuthEndpoints.CurrentUser(context)!, id, cancellationToken) is DeleteDiaperResult.Deleted ? Results.NoContent() : DiaperNotFound();

    private static async Task<IResult> ListAsync(
        Guid babyId, string? cursor, int? limit, DiaperService diapers, HttpContext context, CancellationToken cancellationToken) =>
        await diapers.ListAsync(AuthEndpoints.CurrentUser(context)!, babyId, cursor, limit, cancellationToken) switch
        {
            ListDiapersResult.Page page => Results.Ok(new DiaperPageResponse(page.Entries.Select(ToResponse), page.Next)),
            ListDiapersResult.InvalidCursor => AuthEndpoints.ValidationProblem(new Dictionary<string, string> { ["cursor"] = "invalid" }),
            _ => BabyNotFound(),
        };

    private static DiaperInput Input(
        DateTimeOffset? time, bool? wet, bool? dirty, bool? rash, string? color, string? consistency, string? notes) =>
        new(time, wet ?? false, dirty ?? false, rash ?? false, notes, color, consistency);

    private static IResult BabyNotFound() =>
        Results.Json(new ErrorResponse("babyNotFound"), statusCode: StatusCodes.Status404NotFound);

    private static IResult DiaperNotFound() =>
        Results.Json(new ErrorResponse("diaperNotFound"), statusCode: StatusCodes.Status404NotFound);

    private static DiaperResponse ToResponse(DiaperEntry entry)
    {
        var diaper = entry.Diaper;
        return new DiaperResponse(
            diaper.Id,
            diaper.BabyId,
            diaper.Time,
            diaper.Wet,
            diaper.Dirty,
            diaper.Rash,
            diaper.Color is { } color ? DiaperFields.Format(color) : null,
            diaper.Consistency is { } consistency ? DiaperFields.Format(consistency) : null,
            diaper.Notes,
            UserNameResponse.From(entry.LoggedBy),
            UserNameResponse.From(entry.UpdatedBy),
            diaper.CreatedAt,
            diaper.UpdatedAt);
    }
}
