using Nala.Api.Auth;
using Nala.Api.Entries;
using Nala.Core.HealthEntries;

namespace Nala.Api.HealthEntries;

/// <summary>A new health entry, with its id generated by the client. The unit is ignored without an amount.</summary>
public sealed record CreateHealthEntryRequest(
    Guid? Id, Guid? BabyId, DateTimeOffset? Time, string? Name, decimal? Amount, string? Unit, decimal? Temperature, string? Notes);

/// <summary>Replaces every field; the baby can't change.</summary>
public sealed record UpdateHealthEntryRequest(DateTimeOffset? Time, string? Name, decimal? Amount, string? Unit, decimal? Temperature, string? Notes);

public sealed record HealthEntryResponse(
    Guid Id,
    Guid BabyId,
    DateTimeOffset Time,
    string? Name,
    decimal? Amount,
    string? Unit,
    decimal? Temperature,
    string? Notes,
    UserNameResponse LoggedBy,
    UserNameResponse UpdatedBy,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

/// <summary>Newest first; <c>Next</c> is the cursor of the following page, null after the last one.</summary>
public sealed record HealthEntryPageResponse(IEnumerable<HealthEntryResponse> Entries, string? Next);

/// <summary>A recently given name with the dose of its latest entry (no dose when that entry had none).</summary>
public sealed record RecentMedicineResponse(string Name, decimal? Amount, string? Unit);

/// <summary>A baby's health entries (spec 09). Every member may add, edit and delete any dose (fallback session policy).</summary>
public static class HealthEntryEndpoints
{
    public static IServiceCollection AddNalaHealthEntries(this IServiceCollection services) =>
        services.AddScoped<HealthEntryService>();

    public static IEndpointRouteBuilder MapNalaHealthEntries(this IEndpointRouteBuilder endpoints)
    {
        var healthEntries = endpoints.MapGroup("/api/health-entries");
        healthEntries.MapPost("", CreateAsync);
        healthEntries.MapGet("/{id:guid}", GetAsync);
        healthEntries.MapPut("/{id:guid}", UpdateAsync);
        healthEntries.MapDelete("/{id:guid}", DeleteAsync);

        endpoints.MapGet("/api/babies/{babyId:guid}/health-entries", ListAsync);
        endpoints.MapGet("/api/babies/{babyId:guid}/health-entries/recent", RecentAsync);
        return endpoints;
    }

    /// <summary>201 for a new dose; 200 with the stored dose when its id exists already (a re-sent request).</summary>
    private static async Task<IResult> CreateAsync(
        CreateHealthEntryRequest request, HealthEntryService healthEntries, HttpContext context, CancellationToken cancellationToken)
    {
        var missing = new Dictionary<string, string>();
        if (request.Id is null)
        {
            missing["id"] = "required";
        }

        if (request.BabyId is null)
        {
            missing["babyId"] = "required";
        }

        if (missing.Count > 0)
        {
            return AuthEndpoints.ValidationProblem(missing);
        }

        var input = new HealthEntryInput(request.Time, request.Name, request.Amount, request.Unit, request.Temperature, request.Notes);
        return await healthEntries.CreateAsync(AuthEndpoints.CurrentUser(context)!, request.Id!.Value, request.BabyId!.Value, input, cancellationToken) switch
        {
            CreateHealthEntryResult.Created created => Results.Created($"/api/health-entries/{created.Entry.HealthEntry.Id}", ToResponse(created.Entry)),
            CreateHealthEntryResult.AlreadyExists existing => Results.Ok(ToResponse(existing.Entry)),
            CreateHealthEntryResult.Invalid invalid => AuthEndpoints.ValidationProblem(invalid.Errors),
            _ => BabyNotFound(),
        };
    }

    private static async Task<IResult> GetAsync(Guid id, HealthEntryService healthEntries, CancellationToken cancellationToken) =>
        await healthEntries.GetAsync(id, cancellationToken) is { } entry ? Results.Ok(ToResponse(entry)) : HealthEntryNotFound();

    private static async Task<IResult> UpdateAsync(
        Guid id, UpdateHealthEntryRequest request, HealthEntryService healthEntries, HttpContext context, CancellationToken cancellationToken) =>
        await healthEntries.UpdateAsync(
                AuthEndpoints.CurrentUser(context)!,
                id,
                new HealthEntryInput(request.Time, request.Name, request.Amount, request.Unit, request.Temperature, request.Notes),
                cancellationToken) switch
        {
            UpdateHealthEntryResult.Updated updated => Results.Ok(ToResponse(updated.Entry)),
            UpdateHealthEntryResult.Invalid invalid => AuthEndpoints.ValidationProblem(invalid.Errors),
            _ => HealthEntryNotFound(),
        };

    private static async Task<IResult> DeleteAsync(Guid id, HealthEntryService healthEntries, CancellationToken cancellationToken) =>
        await healthEntries.DeleteAsync(id, cancellationToken) is DeleteHealthEntryResult.Deleted ? Results.NoContent() : HealthEntryNotFound();

    private static async Task<IResult> ListAsync(
        Guid babyId, string? cursor, int? limit, HealthEntryService healthEntries, CancellationToken cancellationToken) =>
        await healthEntries.ListAsync(babyId, cursor, limit, cancellationToken) switch
        {
            ListHealthEntriesResult.Page page => Results.Ok(new HealthEntryPageResponse(page.Entries.Select(ToResponse), page.Next)),
            ListHealthEntriesResult.InvalidCursor => AuthEndpoints.ValidationProblem(new Dictionary<string, string> { ["cursor"] = "invalid" }),
            _ => BabyNotFound(),
        };

    /// <summary>At most 5 names, distinct whatever their case, most recently given first.</summary>
    private static async Task<IResult> RecentAsync(Guid babyId, HealthEntryService healthEntries, CancellationToken cancellationToken) =>
        await healthEntries.RecentAsync(babyId, cancellationToken) is RecentMedicinesResult.Found found
            ? Results.Ok(found.HealthEntries.Select(m => new RecentMedicineResponse(
                m.Name, m.Amount, m.Unit is { } unit ? HealthEntryFields.Format(unit) : null)))
            : BabyNotFound();

    private static IResult BabyNotFound() =>
        Results.Json(new ErrorResponse("babyNotFound"), statusCode: StatusCodes.Status404NotFound);

    private static IResult HealthEntryNotFound() =>
        Results.Json(new ErrorResponse("healthEntryNotFound"), statusCode: StatusCodes.Status404NotFound);

    private static HealthEntryResponse ToResponse(HealthEntryDetails entry)
    {
        var healthEntry = entry.HealthEntry;
        return new HealthEntryResponse(
            healthEntry.Id,
            healthEntry.BabyId,
            healthEntry.Time,
            healthEntry.Name,
            healthEntry.Amount,
            healthEntry.Unit is { } unit ? HealthEntryFields.Format(unit) : null,
            healthEntry.Temperature,
            healthEntry.Notes,
            UserNameResponse.From(entry.LoggedBy),
            UserNameResponse.From(entry.UpdatedBy),
            healthEntry.CreatedAt,
            healthEntry.UpdatedAt);
    }
}
