namespace Nala.Core.HealthEntries;

/// <summary>
/// One dose of a medicine or supplement given to a baby (spec 09): a time, a free-text name, an optional amount with its
/// unit, and notes. The id is generated by the client, so re-sending a queued dose is idempotent.
/// </summary>
public class HealthEntry
{
    public Guid Id { get; init; }

    public Guid BabyId { get; init; }

    public DateTimeOffset Time { get; set; }

    /// <summary>Trimmed, 1 to <see cref="HealthEntryFields.NameMaxLength"/> characters.</summary>
    public string Name { get; set; } = "";

    /// <summary>0.01 to 1000, at most 2 decimals; null when not given.</summary>
    public decimal? Amount { get; set; }

    /// <summary>Only with an amount; null otherwise.</summary>
    public DoseUnit? Unit { get; set; }

    public string? Notes { get; set; }

    public Guid LoggedByUserId { get; init; }

    public DateTimeOffset CreatedAt { get; init; }

    public DateTimeOffset UpdatedAt { get; set; }

    public Guid UpdatedByUserId { get; set; }
}
