namespace Nala.Core.HealthEntries;

/// <summary>
/// One health event of a baby (spec 09): a time, an optional free-text medicine name with an optional amount and unit,
/// an optional temperature, and notes; at least a name or a temperature. The id is generated by the client, so
/// re-sending a queued entry is idempotent.
/// </summary>
public class HealthEntry
{
    public Guid Id { get; init; }

    public Guid BabyId { get; init; }

    public DateTimeOffset Time { get; set; }

    /// <summary>Trimmed, 1 to <see cref="HealthEntryFields.NameMaxLength"/> characters; null when not given.</summary>
    public string? Name { get; set; }

    /// <summary>0.01 to 1000, at most 2 decimals; null when not given.</summary>
    public decimal? Amount { get; set; }

    /// <summary>Only with an amount; null otherwise.</summary>
    public DoseUnit? Unit { get; set; }

    /// <summary>°C, 30.0 to 45.0, at most 1 decimal; null when not given.</summary>
    public decimal? Temperature { get; set; }

    public string? Notes { get; set; }

    public Guid LoggedByUserId { get; init; }

    public DateTimeOffset CreatedAt { get; init; }

    public DateTimeOffset UpdatedAt { get; set; }

    public Guid UpdatedByUserId { get; set; }
}
