using Nala.Api.Auth;
using Nala.Api.Entries;
using Nala.Core.GrowthEntries;

namespace Nala.Api.GrowthEntries;

/// <summary>
/// A new growth entry, with its id generated by the client; the fields of the other kind are ignored. The weight is a decimal so a
/// fractional one can be refused.
/// </summary>
public sealed record CreateGrowthEntryRequest(
    Guid? Id,
    Guid? BabyId,
    string? Kind,
    DateOnly? Date,
    decimal? WeightG,
    decimal? LengthCm,
    decimal? HeadCircumferenceCm,
    string? Milestone,
    string? Title,
    string? Notes)
{
    public GrowthEntryInput ToInput() => new(Date, WeightG, LengthCm, HeadCircumferenceCm, Notes, Milestone, Title);
}

/// <summary>Replaces every field of the entry's kind (the others are ignored); the baby and the kind can't change.</summary>
public sealed record UpdateGrowthEntryRequest(
    DateOnly? Date, decimal? WeightG, decimal? LengthCm, decimal? HeadCircumferenceCm, string? Milestone, string? Title, string? Notes)
{
    public GrowthEntryInput ToInput() => new(Date, WeightG, LengthCm, HeadCircumferenceCm, Notes, Milestone, Title);
}

public sealed record GrowthEntryResponse(
    Guid Id,
    Guid BabyId,
    string Kind,
    DateOnly Date,
    int? WeightG,
    decimal? LengthCm,
    decimal? HeadCircumferenceCm,
    string? Milestone,
    string? Title,
    string? Notes,
    UserNameResponse LoggedBy,
    UserNameResponse UpdatedBy,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

/// <summary>Newest first; <c>Next</c> is the cursor of the following page, null after the last one.</summary>
public sealed record GrowthEntryPageResponse(IEnumerable<GrowthEntryResponse> Entries, string? Next);

/// <summary>The latest value of a measure (grams for the weight, cm otherwise), its date, and whether it is the birth value.</summary>
public sealed record LatestMeasureResponse(decimal Value, DateOnly Date, bool Birth);

public sealed record GrowthLatestResponse(LatestMeasureResponse? Weight, LatestMeasureResponse? Length, LatestMeasureResponse? HeadCircumference);

/// <summary>A baby's growth entries (spec 10). Every member may add, edit and delete any entry (fallback session policy).</summary>
public static class GrowthEntryEndpoints
{
    public static IServiceCollection AddNalaGrowthEntries(this IServiceCollection services) =>
        services.AddScoped<GrowthEntryService>();

    public static IEndpointRouteBuilder MapNalaGrowthEntries(this IEndpointRouteBuilder endpoints)
    {
        var growthEntries = endpoints.MapGroup("/api/growth-entries");
        growthEntries.MapPost("", CreateAsync);
        growthEntries.MapGet("/{id:guid}", GetAsync);
        growthEntries.MapPut("/{id:guid}", UpdateAsync);
        growthEntries.MapDelete("/{id:guid}", DeleteAsync);

        endpoints.MapGet("/api/babies/{babyId:guid}/growth-entries", ListAsync);
        endpoints.MapGet("/api/babies/{babyId:guid}/growth-entries/latest", LatestAsync);
        return endpoints;
    }

    /// <summary>201 for a new entry; 200 with the stored entry when its id exists already (a re-sent request).</summary>
    private static async Task<IResult> CreateAsync(
        CreateGrowthEntryRequest request, GrowthEntryService growthEntries, HttpContext context, CancellationToken cancellationToken)
    {
        var missing = new Dictionary<string, string>();
        if (request.Id is null)
        {
            missing["id"] = "required";
        }

        if (request.BabyId is null)
        {
            missing["babyId"] = "required";
        }

        if (missing.Count > 0)
        {
            return AuthEndpoints.ValidationProblem(missing);
        }

        return await growthEntries.CreateAsync(
                AuthEndpoints.CurrentUser(context)!, request.Id!.Value, request.BabyId!.Value, request.Kind, request.ToInput(), cancellationToken) switch
        {
            CreateGrowthEntryResult.Created created => Results.Created($"/api/growth-entries/{created.Entry.GrowthEntry.Id}", ToResponse(created.Entry)),
            CreateGrowthEntryResult.AlreadyExists existing => Results.Ok(ToResponse(existing.Entry)),
            CreateGrowthEntryResult.Invalid invalid => AuthEndpoints.ValidationProblem(invalid.Errors),
            _ => BabyNotFound(),
        };
    }

    private static async Task<IResult> GetAsync(Guid id, GrowthEntryService growthEntries, CancellationToken cancellationToken) =>
        await growthEntries.GetAsync(id, cancellationToken) is { } entry ? Results.Ok(ToResponse(entry)) : GrowthEntryNotFound();

    private static async Task<IResult> UpdateAsync(
        Guid id, UpdateGrowthEntryRequest request, GrowthEntryService growthEntries, HttpContext context, CancellationToken cancellationToken) =>
        await growthEntries.UpdateAsync(AuthEndpoints.CurrentUser(context)!, id, request.ToInput(), cancellationToken) switch
        {
            UpdateGrowthEntryResult.Updated updated => Results.Ok(ToResponse(updated.Entry)),
            UpdateGrowthEntryResult.Invalid invalid => AuthEndpoints.ValidationProblem(invalid.Errors),
            _ => GrowthEntryNotFound(),
        };

    private static async Task<IResult> DeleteAsync(Guid id, GrowthEntryService growthEntries, CancellationToken cancellationToken) =>
        await growthEntries.DeleteAsync(id, cancellationToken) is DeleteGrowthEntryResult.Deleted ? Results.NoContent() : GrowthEntryNotFound();

    private static async Task<IResult> ListAsync(
        Guid babyId, string? cursor, int? limit, GrowthEntryService growthEntries, CancellationToken cancellationToken) =>
        await growthEntries.ListAsync(babyId, cursor, limit, cancellationToken) switch
        {
            ListGrowthEntriesResult.Page page => Results.Ok(new GrowthEntryPageResponse(page.Entries.Select(ToResponse), page.Next)),
            ListGrowthEntriesResult.InvalidCursor => AuthEndpoints.ValidationProblem(new Dictionary<string, string> { ["cursor"] = "invalid" }),
            _ => BabyNotFound(),
        };

    /// <summary>Each measure from its most recent measurement, else from the birth fields (<c>birth: true</c>), else null.</summary>
    private static async Task<IResult> LatestAsync(Guid babyId, GrowthEntryService growthEntries, CancellationToken cancellationToken) =>
        await growthEntries.LatestAsync(babyId, cancellationToken) is LatestGrowthResult.Found { Latest: var latest }
            ? Results.Ok(new GrowthLatestResponse(ToResponse(latest.Weight), ToResponse(latest.Length), ToResponse(latest.HeadCircumference)))
            : BabyNotFound();

    private static IResult BabyNotFound() =>
        Results.Json(new ErrorResponse("babyNotFound"), statusCode: StatusCodes.Status404NotFound);

    private static IResult GrowthEntryNotFound() =>
        Results.Json(new ErrorResponse("growthEntryNotFound"), statusCode: StatusCodes.Status404NotFound);

    private static LatestMeasureResponse? ToResponse(LatestMeasure? measure) =>
        measure is null ? null : new LatestMeasureResponse(measure.Value, measure.Date, measure.Birth);

    private static GrowthEntryResponse ToResponse(GrowthEntryDetails entry)
    {
        var growthEntry = entry.GrowthEntry;
        return new GrowthEntryResponse(
            growthEntry.Id,
            growthEntry.BabyId,
            GrowthEntryFields.Format(growthEntry.Kind),
            growthEntry.Date,
            growthEntry.WeightG,
            growthEntry.LengthCm,
            growthEntry.HeadCircumferenceCm,
            growthEntry.Milestone is { } milestone ? GrowthEntryFields.FormatMilestone(milestone) : null,
            growthEntry.Title,
            growthEntry.Notes,
            UserNameResponse.From(entry.LoggedBy),
            UserNameResponse.From(entry.UpdatedBy),
            growthEntry.CreatedAt,
            growthEntry.UpdatedAt);
    }
}
