namespace Nala.Core.Feeds;

/// <summary>
/// One timed stretch of a breastfeed on one side (spec 05). Its id is generated by the client, so re-sending a queued
/// timer action is idempotent. At most one segment of a feed is open (no end yet): the side running now.
/// </summary>
public class BreastFeedSegment
{
    public Guid Id { get; init; }

    public Guid FeedId { get; init; }

    public BreastSide Side { get; init; }

    public DateTimeOffset StartedAt { get; init; }

    /// <summary>Null while this side runs.</summary>
    public DateTimeOffset? EndedAt { get; set; }
}
