namespace Nala.Core.Feeds;

/// <summary>
/// One feeding of a baby (spec 05). A single entity for every kind; the fields of the other kinds are null.
/// The id is generated by the client, so re-sending a queued feed is idempotent.
/// </summary>
public class Feed
{
    public Guid Id { get; init; }

    public Guid BabyId { get; init; }

    public FeedKind Kind { get; init; }

    public DateTimeOffset StartTime { get; set; }

    /// <summary>Breastfeed only: the end of its last segment; null while it is live (a side runs).</summary>
    public DateTimeOffset? EndTime { get; set; }

    public string? Notes { get; set; }

    /// <summary>Bottle only.</summary>
    public MilkType? MilkType { get; set; }

    /// <summary>Bottle only.</summary>
    public int? AmountMl { get; set; }

    /// <summary>Solids only; optional.</summary>
    public MealType? MealType { get; set; }

    /// <summary>Solids only.</summary>
    public string? Food { get; set; }

    /// <summary>Solids only; optional.</summary>
    public SolidsReaction? Reaction { get; set; }

    /// <summary>Breastfeed only: its timed stretches per side, oldest first.</summary>
    public List<BreastFeedSegment> Segments { get; init; } = [];

    public Guid LoggedByUserId { get; init; }

    public DateTimeOffset CreatedAt { get; init; }

    public DateTimeOffset UpdatedAt { get; set; }

    public Guid UpdatedByUserId { get; set; }
}
