using Nala.Api.Auth;
using Nala.Api.Entries;
using Nala.Core.Pumps;

namespace Nala.Api.Pumps;

/// <summary>
/// A new pumping session, with its id generated by the client, typed by hand: <c>EndTime</c> is required. Volumes are
/// decimals so a fractional one gets a validation error.
/// </summary>
public sealed record CreatePumpRequest(
    Guid? Id, Guid? BabyId, DateTimeOffset? StartTime, DateTimeOffset? EndTime, decimal? LeftMl, decimal? RightMl, string? Notes);

/// <summary>Replaces the start time, end time, volumes and notes; the baby can't change. A live session takes no end time.</summary>
public sealed record UpdatePumpRequest(DateTimeOffset? StartTime, DateTimeOffset? EndTime, decimal? LeftMl, decimal? RightMl, string? Notes);

/// <summary>A pumping session; <c>EndTime</c> is null while it is live, a null volume wasn't recorded.</summary>
public sealed record PumpResponse(
    Guid Id,
    Guid BabyId,
    DateTimeOffset StartTime,
    DateTimeOffset? EndTime,
    int? LeftMl,
    int? RightMl,
    string? Notes,
    UserNameResponse LoggedBy,
    UserNameResponse UpdatedBy,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

/// <summary>Newest first; <c>Next</c> is the cursor of the following page, null after the last one.</summary>
public sealed record PumpPageResponse(IEnumerable<PumpResponse> Entries, string? Next);

/// <summary>A baby's pumping sessions (spec 08). Every member may add, edit and delete any session (fallback session policy).</summary>
public static class PumpEndpoints
{
    public static IServiceCollection AddNalaPumps(this IServiceCollection services) =>
        services.AddScoped<PumpService>();

    public static IEndpointRouteBuilder MapNalaPumps(this IEndpointRouteBuilder endpoints)
    {
        var pumps = endpoints.MapGroup("/api/pumps");
        pumps.MapPost("", CreateAsync);
        pumps.MapGet("/{id:guid}", GetAsync);
        pumps.MapPut("/{id:guid}", UpdateAsync);
        pumps.MapDelete("/{id:guid}", DeleteAsync);

        endpoints.MapGet("/api/babies/{babyId:guid}/pumps", ListAsync);
        return endpoints;
    }

    /// <summary>201 for a new session; 200 with the stored session when its id exists already (a re-sent request).</summary>
    private static async Task<IResult> CreateAsync(
        CreatePumpRequest request, PumpService pumps, HttpContext context, CancellationToken cancellationToken)
    {
        var missing = new Dictionary<string, string>();
        if (request.Id is null)
        {
            missing["id"] = "required";
        }

        if (request.BabyId is null)
        {
            missing["babyId"] = "required";
        }

        if (missing.Count > 0)
        {
            return AuthEndpoints.ValidationProblem(missing);
        }

        var input = new PumpInput(request.StartTime, request.EndTime, request.LeftMl, request.RightMl, request.Notes);
        return await pumps.CreateAsync(AuthEndpoints.CurrentUser(context)!, request.Id!.Value, request.BabyId!.Value, input, cancellationToken) switch
        {
            CreatePumpResult.Created created => Results.Created($"/api/pumps/{created.Entry.Pump.Id}", ToResponse(created.Entry)),
            CreatePumpResult.AlreadyExists existing => Results.Ok(ToResponse(existing.Entry)),
            CreatePumpResult.Invalid invalid => AuthEndpoints.ValidationProblem(invalid.Errors),
            _ => BabyNotFound(),
        };
    }

    private static async Task<IResult> GetAsync(Guid id, PumpService pumps, CancellationToken cancellationToken) =>
        await pumps.GetAsync(id, cancellationToken) is { } entry ? Results.Ok(ToResponse(entry)) : PumpNotFound();

    private static async Task<IResult> UpdateAsync(
        Guid id, UpdatePumpRequest request, PumpService pumps, HttpContext context, CancellationToken cancellationToken) =>
        await pumps.UpdateAsync(
                AuthEndpoints.CurrentUser(context)!,
                id,
                new PumpInput(request.StartTime, request.EndTime, request.LeftMl, request.RightMl, request.Notes),
                cancellationToken) switch
        {
            UpdatePumpResult.Updated updated => Results.Ok(ToResponse(updated.Entry)),
            UpdatePumpResult.Invalid invalid => AuthEndpoints.ValidationProblem(invalid.Errors),
            _ => PumpNotFound(),
        };

    private static async Task<IResult> DeleteAsync(Guid id, PumpService pumps, CancellationToken cancellationToken) =>
        await pumps.DeleteAsync(id, cancellationToken) is DeletePumpResult.Deleted ? Results.NoContent() : PumpNotFound();

    private static async Task<IResult> ListAsync(
        Guid babyId, string? cursor, int? limit, PumpService pumps, CancellationToken cancellationToken) =>
        await pumps.ListAsync(babyId, cursor, limit, cancellationToken) switch
        {
            ListPumpsResult.Page page => Results.Ok(new PumpPageResponse(page.Entries.Select(ToResponse), page.Next)),
            ListPumpsResult.InvalidCursor => AuthEndpoints.ValidationProblem(new Dictionary<string, string> { ["cursor"] = "invalid" }),
            _ => BabyNotFound(),
        };

    private static IResult BabyNotFound() =>
        Results.Json(new ErrorResponse("babyNotFound"), statusCode: StatusCodes.Status404NotFound);

    private static IResult PumpNotFound() =>
        Results.Json(new ErrorResponse("pumpNotFound"), statusCode: StatusCodes.Status404NotFound);

    internal static PumpResponse ToResponse(PumpEntry entry)
    {
        var pump = entry.Pump;
        return new PumpResponse(
            pump.Id,
            pump.BabyId,
            pump.StartTime,
            pump.EndTime,
            pump.LeftMl,
            pump.RightMl,
            pump.Notes,
            UserNameResponse.From(entry.LoggedBy),
            UserNameResponse.From(entry.UpdatedBy),
            pump.CreatedAt,
            pump.UpdatedAt);
    }
}
