namespace Nala.Core.Sleeps;

/// <summary>
/// One sleep of a baby (spec 06): a start time, an end time and notes. The id is generated by the client, so
/// re-sending a queued sleep is idempotent.
/// </summary>
public class Sleep
{
    public Guid Id { get; init; }

    public Guid BabyId { get; init; }

    public DateTimeOffset StartTime { get; set; }

    /// <summary>Null while the sleep is live (its timer runs).</summary>
    public DateTimeOffset? EndTime { get; set; }

    public string? Notes { get; set; }

    public Guid LoggedByUserId { get; init; }

    public DateTimeOffset CreatedAt { get; init; }

    public DateTimeOffset UpdatedAt { get; set; }

    public Guid UpdatedByUserId { get; set; }
}
