using Nala.Api.Auth;
using Nala.Api.Entries;
using Nala.Core.Medications;

namespace Nala.Api.Medications;

/// <summary>A new dose, with its id generated by the client. The unit is ignored without an amount.</summary>
public sealed record CreateMedicationRequest(
    Guid? Id, Guid? BabyId, DateTimeOffset? Time, string? Name, decimal? Amount, string? Unit, string? Notes);

/// <summary>Replaces every field; the baby can't change.</summary>
public sealed record UpdateMedicationRequest(DateTimeOffset? Time, string? Name, decimal? Amount, string? Unit, string? Notes);

public sealed record MedicationResponse(
    Guid Id,
    Guid BabyId,
    DateTimeOffset Time,
    string Name,
    decimal? Amount,
    string? Unit,
    string? Notes,
    UserNameResponse LoggedBy,
    UserNameResponse UpdatedBy,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

/// <summary>Newest first; <c>Next</c> is the cursor of the following page, null after the last one.</summary>
public sealed record MedicationPageResponse(IEnumerable<MedicationResponse> Entries, string? Next);

/// <summary>A baby's medication doses (spec 09). Every member may add, edit and delete any dose (fallback session policy).</summary>
public static class MedicationEndpoints
{
    public static IServiceCollection AddNalaMedications(this IServiceCollection services) =>
        services.AddScoped<MedicationService>();

    public static IEndpointRouteBuilder MapNalaMedications(this IEndpointRouteBuilder endpoints)
    {
        var medications = endpoints.MapGroup("/api/medications");
        medications.MapPost("", CreateAsync);
        medications.MapGet("/{id:guid}", GetAsync);
        medications.MapPut("/{id:guid}", UpdateAsync);
        medications.MapDelete("/{id:guid}", DeleteAsync);

        endpoints.MapGet("/api/babies/{babyId:guid}/medications", ListAsync);
        return endpoints;
    }

    /// <summary>201 for a new dose; 200 with the stored dose when its id exists already (a re-sent request).</summary>
    private static async Task<IResult> CreateAsync(
        CreateMedicationRequest request, MedicationService medications, HttpContext context, CancellationToken cancellationToken)
    {
        var missing = new Dictionary<string, string>();
        if (request.Id is null)
        {
            missing["id"] = "required";
        }

        if (request.BabyId is null)
        {
            missing["babyId"] = "required";
        }

        if (missing.Count > 0)
        {
            return AuthEndpoints.ValidationProblem(missing);
        }

        var input = new MedicationInput(request.Time, request.Name, request.Amount, request.Unit, request.Notes);
        return await medications.CreateAsync(AuthEndpoints.CurrentUser(context)!, request.Id!.Value, request.BabyId!.Value, input, cancellationToken) switch
        {
            CreateMedicationResult.Created created => Results.Created($"/api/medications/{created.Entry.Medication.Id}", ToResponse(created.Entry)),
            CreateMedicationResult.AlreadyExists existing => Results.Ok(ToResponse(existing.Entry)),
            CreateMedicationResult.Invalid invalid => AuthEndpoints.ValidationProblem(invalid.Errors),
            _ => BabyNotFound(),
        };
    }

    private static async Task<IResult> GetAsync(Guid id, MedicationService medications, CancellationToken cancellationToken) =>
        await medications.GetAsync(id, cancellationToken) is { } entry ? Results.Ok(ToResponse(entry)) : MedicationNotFound();

    private static async Task<IResult> UpdateAsync(
        Guid id, UpdateMedicationRequest request, MedicationService medications, HttpContext context, CancellationToken cancellationToken) =>
        await medications.UpdateAsync(
                AuthEndpoints.CurrentUser(context)!,
                id,
                new MedicationInput(request.Time, request.Name, request.Amount, request.Unit, request.Notes),
                cancellationToken) switch
        {
            UpdateMedicationResult.Updated updated => Results.Ok(ToResponse(updated.Entry)),
            UpdateMedicationResult.Invalid invalid => AuthEndpoints.ValidationProblem(invalid.Errors),
            _ => MedicationNotFound(),
        };

    private static async Task<IResult> DeleteAsync(Guid id, MedicationService medications, CancellationToken cancellationToken) =>
        await medications.DeleteAsync(id, cancellationToken) is DeleteMedicationResult.Deleted ? Results.NoContent() : MedicationNotFound();

    private static async Task<IResult> ListAsync(
        Guid babyId, string? cursor, int? limit, MedicationService medications, CancellationToken cancellationToken) =>
        await medications.ListAsync(babyId, cursor, limit, cancellationToken) switch
        {
            ListMedicationsResult.Page page => Results.Ok(new MedicationPageResponse(page.Entries.Select(ToResponse), page.Next)),
            ListMedicationsResult.InvalidCursor => AuthEndpoints.ValidationProblem(new Dictionary<string, string> { ["cursor"] = "invalid" }),
            _ => BabyNotFound(),
        };

    private static IResult BabyNotFound() =>
        Results.Json(new ErrorResponse("babyNotFound"), statusCode: StatusCodes.Status404NotFound);

    private static IResult MedicationNotFound() =>
        Results.Json(new ErrorResponse("medicationNotFound"), statusCode: StatusCodes.Status404NotFound);

    private static MedicationResponse ToResponse(MedicationEntry entry)
    {
        var medication = entry.Medication;
        return new MedicationResponse(
            medication.Id,
            medication.BabyId,
            medication.Time,
            medication.Name,
            medication.Amount,
            medication.Unit is { } unit ? MedicationFields.Format(unit) : null,
            medication.Notes,
            UserNameResponse.From(entry.LoggedBy),
            UserNameResponse.From(entry.UpdatedBy),
            medication.CreatedAt,
            medication.UpdatedAt);
    }
}
