namespace Nala.Core.Pumps;

/// <summary>
/// One pumping session for a baby (spec 08): a start time, an end time, the volume pumped from each breast and notes.
/// The id is generated by the client, so re-sending a queued session is idempotent.
/// </summary>
public class Pump
{
    public Guid Id { get; init; }

    public Guid BabyId { get; init; }

    public DateTimeOffset StartTime { get; set; }

    /// <summary>Null while the session is live (its timer runs).</summary>
    public DateTimeOffset? EndTime { get; set; }

    /// <summary>Millilitres from the left breast; null when not recorded, 0 when that side gave nothing.</summary>
    public int? LeftMl { get; set; }

    /// <summary>Millilitres from the right breast; null when not recorded, 0 when that side gave nothing.</summary>
    public int? RightMl { get; set; }

    public string? Notes { get; set; }

    public Guid LoggedByUserId { get; init; }

    public DateTimeOffset CreatedAt { get; init; }

    public DateTimeOffset UpdatedAt { get; set; }

    public Guid UpdatedByUserId { get; set; }
}
