using Nala.Api.Auth;
using Nala.Api.Entries;
using Nala.Core.Sleeps;

namespace Nala.Api.Sleeps;

/// <summary>A new sleep, with its id generated by the client, typed by hand: <c>EndTime</c> is required.</summary>
public sealed record CreateSleepRequest(Guid? Id, Guid? BabyId, DateTimeOffset? StartTime, DateTimeOffset? EndTime, string? Notes);

/// <summary>Replaces the start time, end time and notes; the baby can't change. A live sleep takes no end time.</summary>
public sealed record UpdateSleepRequest(DateTimeOffset? StartTime, DateTimeOffset? EndTime, string? Notes);

/// <summary>
/// Starts the sleep's timer at <c>At</c>: creates it live for <c>BabyId</c> when unknown. <c>Queued</c>: sent from a device's
/// offline queue, kept even while another sleep of the baby is live.
/// </summary>
public sealed record StartSleepRequest(Guid? BabyId, DateTimeOffset? At, bool? Queued = null);

/// <summary>Stops the sleep's timer at <c>At</c>, its end time.</summary>
public sealed record StopSleepRequest(DateTimeOffset? At);

/// <summary>A sleep; <c>EndTime</c> is null while it is live.</summary>
public sealed record SleepResponse(
    Guid Id,
    Guid BabyId,
    DateTimeOffset StartTime,
    DateTimeOffset? EndTime,
    string? Notes,
    UserNameResponse LoggedBy,
    UserNameResponse UpdatedBy,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

/// <summary>Newest first; <c>Next</c> is the cursor of the following page, null after the last one.</summary>
public sealed record SleepPageResponse(IEnumerable<SleepResponse> Entries, string? Next);

/// <summary>A baby's sleeps (spec 06). Every member may add, edit and delete any sleep (fallback session policy).</summary>
public static class SleepEndpoints
{
    public static IServiceCollection AddNalaSleeps(this IServiceCollection services) =>
        services.AddScoped<SleepService>();

    public static IEndpointRouteBuilder MapNalaSleeps(this IEndpointRouteBuilder endpoints)
    {
        var sleeps = endpoints.MapGroup("/api/sleeps");
        sleeps.MapPost("", CreateAsync);
        sleeps.MapPost("/{id:guid}/start", StartAsync);
        sleeps.MapPost("/{id:guid}/stop", StopAsync);
        sleeps.MapGet("/{id:guid}", GetAsync);
        sleeps.MapPut("/{id:guid}", UpdateAsync);
        sleeps.MapDelete("/{id:guid}", DeleteAsync);

        endpoints.MapGet("/api/babies/{babyId:guid}/sleeps", ListAsync);
        return endpoints;
    }

    /// <summary>201 for a new sleep; 200 with the stored sleep when its id exists already (a re-sent request).</summary>
    private static async Task<IResult> CreateAsync(
        CreateSleepRequest request, SleepService sleeps, HttpContext context, CancellationToken cancellationToken)
    {
        var missing = new Dictionary<string, string>();
        if (request.Id is null)
        {
            missing["id"] = "required";
        }

        if (request.BabyId is null)
        {
            missing["babyId"] = "required";
        }

        if (missing.Count > 0)
        {
            return AuthEndpoints.ValidationProblem(missing);
        }

        var input = new SleepInput(request.StartTime, request.EndTime, request.Notes);
        return await sleeps.CreateAsync(AuthEndpoints.CurrentUser(context)!, request.Id!.Value, request.BabyId!.Value, input, cancellationToken) switch
        {
            CreateSleepResult.Created created => Results.Created($"/api/sleeps/{created.Entry.Sleep.Id}", ToResponse(created.Entry)),
            CreateSleepResult.AlreadyExists existing => Results.Ok(ToResponse(existing.Entry)),
            CreateSleepResult.Invalid invalid => AuthEndpoints.ValidationProblem(invalid.Errors),
            _ => BabyNotFound(),
        };
    }

    private static async Task<IResult> GetAsync(Guid id, SleepService sleeps, CancellationToken cancellationToken) =>
        await sleeps.GetAsync(id, cancellationToken) is { } entry ? Results.Ok(ToResponse(entry)) : SleepNotFound();

    private static async Task<IResult> UpdateAsync(
        Guid id, UpdateSleepRequest request, SleepService sleeps, HttpContext context, CancellationToken cancellationToken) =>
        await sleeps.UpdateAsync(
                AuthEndpoints.CurrentUser(context)!, id, new SleepInput(request.StartTime, request.EndTime, request.Notes), cancellationToken) switch
        {
            UpdateSleepResult.Updated updated => Results.Ok(ToResponse(updated.Entry)),
            UpdateSleepResult.Invalid invalid => AuthEndpoints.ValidationProblem(invalid.Errors),
            _ => SleepNotFound(),
        };

    private static async Task<IResult> DeleteAsync(Guid id, SleepService sleeps, CancellationToken cancellationToken) =>
        await sleeps.DeleteAsync(id, cancellationToken) is DeleteSleepResult.Deleted ? Results.NoContent() : SleepNotFound();

    private static async Task<IResult> ListAsync(
        Guid babyId, string? cursor, int? limit, SleepService sleeps, CancellationToken cancellationToken) =>
        await sleeps.ListAsync(babyId, cursor, limit, cancellationToken) switch
        {
            ListSleepsResult.Page page => Results.Ok(new SleepPageResponse(page.Entries.Select(ToResponse), page.Next)),
            ListSleepsResult.InvalidCursor => AuthEndpoints.ValidationProblem(new Dictionary<string, string> { ["cursor"] = "invalid" }),
            _ => BabyNotFound(),
        };

    /// <summary>201 when it created the live sleep, 200 otherwise; 409 while another one is live (unless queued).</summary>
    private static async Task<IResult> StartAsync(
        Guid id, StartSleepRequest request, SleepService sleeps, HttpContext context, CancellationToken cancellationToken)
    {
        if (request.BabyId is null)
        {
            return AuthEndpoints.ValidationProblem(new Dictionary<string, string> { ["babyId"] = "required" });
        }

        return TimerResponse(await sleeps.StartAsync(
            AuthEndpoints.CurrentUser(context)!, id, request.BabyId.Value, request.At, request.Queued ?? false, cancellationToken));
    }

    private static async Task<IResult> StopAsync(
        Guid id, StopSleepRequest request, SleepService sleeps, HttpContext context, CancellationToken cancellationToken) =>
        TimerResponse(await sleeps.StopAsync(AuthEndpoints.CurrentUser(context)!, id, request.At, cancellationToken));

    private static IResult TimerResponse(SleepTimerResult result) => result switch
    {
        SleepTimerResult.Created created => Results.Created($"/api/sleeps/{created.Entry.Sleep.Id}", ToResponse(created.Entry)),
        SleepTimerResult.Updated updated => Results.Ok(ToResponse(updated.Entry)),
        SleepTimerResult.Invalid invalid => AuthEndpoints.ValidationProblem(invalid.Errors),
        SleepTimerResult.InProgressExists =>
            Results.Json(new ErrorResponse("sleepInProgress"), statusCode: StatusCodes.Status409Conflict),
        SleepTimerResult.BabyNotFound => BabyNotFound(),
        _ => SleepNotFound(),
    };

    private static IResult BabyNotFound() =>
        Results.Json(new ErrorResponse("babyNotFound"), statusCode: StatusCodes.Status404NotFound);

    private static IResult SleepNotFound() =>
        Results.Json(new ErrorResponse("sleepNotFound"), statusCode: StatusCodes.Status404NotFound);

    internal static SleepResponse ToResponse(SleepEntry entry)
    {
        var sleep = entry.Sleep;
        return new SleepResponse(
            sleep.Id,
            sleep.BabyId,
            sleep.StartTime,
            sleep.EndTime,
            sleep.Notes,
            UserNameResponse.From(entry.LoggedBy),
            UserNameResponse.From(entry.UpdatedBy),
            sleep.CreatedAt,
            sleep.UpdatedAt);
    }
}
