using Nala.Api.Auth;
using Nala.Core.Feeds;

namespace Nala.Api.Feeds;

/// <summary>
/// A new feed, with its id generated by the client. <c>Kind</c> is <c>bottle</c>; a bottle has <c>MilkType</c>
/// (<c>breastMilk</c> or <c>formula</c>) and <c>AmountMl</c>, a decimal so a fractional amount gets a validation code.
/// </summary>
public sealed record CreateFeedRequest(
    Guid? Id,
    Guid? BabyId,
    string? Kind,
    DateTimeOffset? StartTime,
    string? Notes,
    string? MilkType,
    decimal? AmountMl);

/// <summary>Every field of the feed's kind; the baby and the kind can't change.</summary>
public sealed record UpdateFeedRequest(DateTimeOffset? StartTime, string? Notes, string? MilkType, decimal? AmountMl);

public sealed record UserNameResponse(Guid Id, string DisplayName);

/// <summary>Fields of the other kinds are null.</summary>
public sealed record FeedResponse(
    Guid Id,
    Guid BabyId,
    string Kind,
    DateTimeOffset StartTime,
    DateTimeOffset? EndTime,
    string? Notes,
    string? MilkType,
    int? AmountMl,
    UserNameResponse LoggedBy,
    UserNameResponse UpdatedBy,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

/// <summary>Newest first; <c>Next</c> is the cursor of the following page, null after the last one.</summary>
public sealed record FeedPageResponse(IEnumerable<FeedResponse> Entries, string? Next);

public sealed record LastAmountsResponse(int? BreastMilk, int? Formula);

public sealed record BottleDefaultsResponse(string? MilkType, LastAmountsResponse LastAmountMl);

/// <summary>A baby's feeds (spec 05). Every member may add, edit and delete any feed (fallback session policy).</summary>
public static class FeedEndpoints
{
    public static IServiceCollection AddNalaFeeds(this IServiceCollection services) =>
        services.AddScoped<FeedService>();

    public static IEndpointRouteBuilder MapNalaFeeds(this IEndpointRouteBuilder endpoints)
    {
        var feeds = endpoints.MapGroup("/api/feeds");
        feeds.MapPost("", CreateAsync);
        feeds.MapPut("/{id:guid}", UpdateAsync);
        feeds.MapDelete("/{id:guid}", DeleteAsync);

        var ofBaby = endpoints.MapGroup("/api/babies/{babyId:guid}/feeds");
        ofBaby.MapGet("", ListAsync);
        ofBaby.MapGet("/bottle-defaults", BottleDefaultsAsync);
        return endpoints;
    }

    /// <summary>201 for a new feed; 200 with the stored feed when its id exists already (a re-sent request).</summary>
    private static async Task<IResult> CreateAsync(
        CreateFeedRequest request, FeedService feeds, HttpContext context, CancellationToken cancellationToken)
    {
        var missing = new Dictionary<string, string>();
        if (request.Id is null)
        {
            missing["id"] = "required";
        }

        if (request.BabyId is null)
        {
            missing["babyId"] = "required";
        }

        if (missing.Count > 0)
        {
            return AuthEndpoints.ValidationProblem(missing);
        }

        var input = new FeedInput(request.Kind, request.StartTime, request.Notes, request.MilkType, request.AmountMl);
        return await feeds.CreateAsync(AuthEndpoints.CurrentUser(context)!, request.Id!.Value, request.BabyId!.Value, input, cancellationToken) switch
        {
            CreateFeedResult.Created created => Results.Created($"/api/feeds/{created.Entry.Feed.Id}", ToResponse(created.Entry)),
            CreateFeedResult.AlreadyExists existing => Results.Ok(ToResponse(existing.Entry)),
            CreateFeedResult.Invalid invalid => AuthEndpoints.ValidationProblem(invalid.Errors),
            _ => BabyNotFound(),
        };
    }

    private static async Task<IResult> UpdateAsync(
        Guid id, UpdateFeedRequest request, FeedService feeds, HttpContext context, CancellationToken cancellationToken)
    {
        var input = new FeedInput(null, request.StartTime, request.Notes, request.MilkType, request.AmountMl);
        return await feeds.UpdateAsync(AuthEndpoints.CurrentUser(context)!, id, input, cancellationToken) switch
        {
            UpdateFeedResult.Updated updated => Results.Ok(ToResponse(updated.Entry)),
            UpdateFeedResult.Invalid invalid => AuthEndpoints.ValidationProblem(invalid.Errors),
            _ => FeedNotFound(),
        };
    }

    private static async Task<IResult> DeleteAsync(Guid id, FeedService feeds, CancellationToken cancellationToken) =>
        await feeds.DeleteAsync(id, cancellationToken) is DeleteFeedResult.Deleted ? Results.NoContent() : FeedNotFound();

    private static async Task<IResult> ListAsync(
        Guid babyId, string? cursor, int? limit, FeedService feeds, CancellationToken cancellationToken) =>
        await feeds.ListAsync(babyId, cursor, limit, cancellationToken) switch
        {
            ListFeedsResult.Page page => Results.Ok(new FeedPageResponse(page.Entries.Select(ToResponse), page.Next)),
            ListFeedsResult.InvalidCursor => AuthEndpoints.ValidationProblem(new Dictionary<string, string> { ["cursor"] = "invalid" }),
            _ => BabyNotFound(),
        };

    private static async Task<IResult> BottleDefaultsAsync(Guid babyId, FeedService feeds, CancellationToken cancellationToken) =>
        await feeds.GetBottleDefaultsAsync(babyId, cancellationToken) is BottleDefaultsResult.Found { Defaults: var defaults }
            ? Results.Ok(new BottleDefaultsResponse(
                defaults.MilkType is { } milkType ? FeedFields.Format(milkType) : null,
                new LastAmountsResponse(defaults.LastBreastMilkMl, defaults.LastFormulaMl)))
            : BabyNotFound();

    private static IResult BabyNotFound() =>
        Results.Json(new ErrorResponse("babyNotFound"), statusCode: StatusCodes.Status404NotFound);

    private static IResult FeedNotFound() =>
        Results.Json(new ErrorResponse("feedNotFound"), statusCode: StatusCodes.Status404NotFound);

    private static FeedResponse ToResponse(FeedEntry entry)
    {
        var feed = entry.Feed;
        return new FeedResponse(
            feed.Id,
            feed.BabyId,
            FeedFields.Format(feed.Kind),
            feed.StartTime,
            feed.EndTime,
            feed.Notes,
            feed.MilkType is { } milkType ? FeedFields.Format(milkType) : null,
            feed.AmountMl,
            new UserNameResponse(entry.LoggedBy.Id, entry.LoggedBy.DisplayName),
            new UserNameResponse(entry.UpdatedBy.Id, entry.UpdatedBy.DisplayName),
            feed.CreatedAt,
            feed.UpdatedAt);
    }
}
