using Nala.Api.Auth;
using Nala.Core.Feeds;

namespace Nala.Api.Feeds;

/// <summary>
/// A new feed, with its id generated by the client. <c>Kind</c> is <c>bottle</c>, <c>solids</c> or <c>breastfeed</c>
/// (typed by hand: <c>Durations</c> is required; otherwise a breastfeed starts from its timers). A bottle has
/// <c>MilkType</c> (<c>breastMilk</c> or <c>formula</c>) and <c>AmountMl</c>, a decimal so a fractional amount gets a
/// validation code. Solids have <c>Food</c> and, optionally, <c>MealType</c> (<c>breakfast</c>, <c>lunch</c>,
/// <c>dinner</c>, <c>snack</c>) and <c>Reaction</c> (<c>liked</c>, <c>neutral</c>, <c>disliked</c>,
/// <c>allergicReaction</c>). The fields of the other kinds are ignored.
/// </summary>
public sealed record CreateFeedRequest(
    Guid? Id,
    Guid? BabyId,
    string? Kind,
    DateTimeOffset? StartTime,
    string? Notes,
    string? MilkType,
    decimal? AmountMl,
    string? MealType,
    string? Food,
    string? Reaction,
    DurationsRequest? Durations);

/// <summary>
/// Every field of the feed's kind; the baby and the kind can't change. On a breastfeed, <c>Durations</c> (optional)
/// replace its timed segments and save it.
/// </summary>
public sealed record UpdateFeedRequest(
    DateTimeOffset? StartTime,
    string? Notes,
    string? MilkType,
    decimal? AmountMl,
    string? MealType,
    string? Food,
    string? Reaction,
    DurationsRequest? Durations);

/// <summary>A breastfeed's durations typed by hand, in whole seconds; <c>EndedOn</c> (<c>left</c> or <c>right</c>) when both are above 0.</summary>
public sealed record DurationsRequest(int? LeftSeconds, int? RightSeconds, string? EndedOn)
{
    public BreastfeedDurations ToInput() => new(LeftSeconds, RightSeconds, EndedOn);
}

/// <summary>
/// Starts <c>Side</c> (<c>left</c> or <c>right</c>) of a breastfeed at <c>At</c>; <c>SegmentId</c> is generated by the client.
/// <c>Queued</c>: sent from a device's offline queue, kept even while another breastfeed of the baby is in progress.
/// </summary>
public sealed record StartSideRequest(Guid? BabyId, Guid? SegmentId, string? Side, DateTimeOffset? At, bool? Queued = null);

public sealed record StopSideRequest(DateTimeOffset? At);

/// <summary>Saves a breastfeed: ended at <c>At</c>, with the start time and notes of the sheet.</summary>
public sealed record FinishBreastfeedRequest(DateTimeOffset? StartTime, string? Notes, DateTimeOffset? At);

public sealed record UserNameResponse(Guid Id, string DisplayName);

/// <summary>One timed stretch of a breastfeed; <c>EndedAt</c> is null while that side runs.</summary>
public sealed record SegmentResponse(Guid Id, string Side, DateTimeOffset StartedAt, DateTimeOffset? EndedAt);

/// <summary>Fields of the other kinds are null; <c>Segments</c> is empty for other kinds than breastfeed.</summary>
public sealed record FeedResponse(
    Guid Id,
    Guid BabyId,
    string Kind,
    DateTimeOffset StartTime,
    DateTimeOffset? EndTime,
    string? Notes,
    string? MilkType,
    int? AmountMl,
    string? MealType,
    string? Food,
    string? Reaction,
    IEnumerable<SegmentResponse> Segments,
    UserNameResponse LoggedBy,
    UserNameResponse UpdatedBy,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt);

/// <summary>Newest first; <c>Next</c> is the cursor of the following page, null after the last one.</summary>
public sealed record FeedPageResponse(IEnumerable<FeedResponse> Entries, string? Next);

public sealed record LastAmountsResponse(int? BreastMilk, int? Formula);

public sealed record BottleDefaultsResponse(string? MilkType, LastAmountsResponse LastAmountMl);

/// <summary>The breastfeed in progress (null when none) and the side the latest saved one ended on.</summary>
public sealed record BreastfeedStateResponse(FeedResponse? InProgress, string? LastSide);

/// <summary>A baby's feeds (spec 05). Every member may add, edit and delete any feed (fallback session policy).</summary>
public static class FeedEndpoints
{
    public static IServiceCollection AddNalaFeeds(this IServiceCollection services) =>
        services.AddScoped<FeedService>();

    public static IEndpointRouteBuilder MapNalaFeeds(this IEndpointRouteBuilder endpoints)
    {
        var feeds = endpoints.MapGroup("/api/feeds");
        feeds.MapPost("", CreateAsync);
        feeds.MapGet("/in-progress", InProgressAsync);
        feeds.MapPut("/{id:guid}", UpdateAsync);
        feeds.MapDelete("/{id:guid}", DeleteAsync);
        feeds.MapPost("/{id:guid}/breastfeed/start", StartSideAsync);
        feeds.MapPost("/{id:guid}/breastfeed/stop", StopSideAsync);
        feeds.MapPost("/{id:guid}/breastfeed/finish", FinishAsync);

        var ofBaby = endpoints.MapGroup("/api/babies/{babyId:guid}/feeds");
        ofBaby.MapGet("", ListAsync);
        ofBaby.MapGet("/bottle-defaults", BottleDefaultsAsync);
        ofBaby.MapGet("/breastfeed", BreastfeedStateAsync);
        return endpoints;
    }

    /// <summary>201 for a new feed; 200 with the stored feed when its id exists already (a re-sent request).</summary>
    private static async Task<IResult> CreateAsync(
        CreateFeedRequest request, FeedService feeds, HttpContext context, CancellationToken cancellationToken)
    {
        var missing = new Dictionary<string, string>();
        if (request.Id is null)
        {
            missing["id"] = "required";
        }

        if (request.BabyId is null)
        {
            missing["babyId"] = "required";
        }

        if (missing.Count > 0)
        {
            return AuthEndpoints.ValidationProblem(missing);
        }

        var input = new FeedInput(
            request.Kind, request.StartTime, request.Notes, request.MilkType, request.AmountMl, request.MealType, request.Food, request.Reaction,
            request.Durations?.ToInput());
        return await feeds.CreateAsync(AuthEndpoints.CurrentUser(context)!, request.Id!.Value, request.BabyId!.Value, input, cancellationToken) switch
        {
            CreateFeedResult.Created created => Results.Created($"/api/feeds/{created.Entry.Feed.Id}", ToResponse(created.Entry)),
            CreateFeedResult.AlreadyExists existing => Results.Ok(ToResponse(existing.Entry)),
            CreateFeedResult.Invalid invalid => AuthEndpoints.ValidationProblem(invalid.Errors),
            _ => BabyNotFound(),
        };
    }

    /// <summary>Every breastfeed in progress, of every baby, oldest start first: what other devices poll (spec 05).</summary>
    private static async Task<IResult> InProgressAsync(FeedService feeds, CancellationToken cancellationToken) =>
        Results.Ok((await feeds.ListInProgressBreastfeedsAsync(cancellationToken)).Select(ToResponse));

    private static async Task<IResult> UpdateAsync(
        Guid id, UpdateFeedRequest request, FeedService feeds, HttpContext context, CancellationToken cancellationToken)
    {
        var input = new FeedInput(
            null, request.StartTime, request.Notes, request.MilkType, request.AmountMl, request.MealType, request.Food, request.Reaction,
            request.Durations?.ToInput());
        return await feeds.UpdateAsync(AuthEndpoints.CurrentUser(context)!, id, input, cancellationToken) switch
        {
            UpdateFeedResult.Updated updated => Results.Ok(ToResponse(updated.Entry)),
            UpdateFeedResult.Invalid invalid => AuthEndpoints.ValidationProblem(invalid.Errors),
            _ => FeedNotFound(),
        };
    }

    private static async Task<IResult> DeleteAsync(Guid id, FeedService feeds, CancellationToken cancellationToken) =>
        await feeds.DeleteAsync(id, cancellationToken) is DeleteFeedResult.Deleted ? Results.NoContent() : FeedNotFound();

    private static async Task<IResult> ListAsync(
        Guid babyId, string? cursor, int? limit, FeedService feeds, CancellationToken cancellationToken) =>
        await feeds.ListAsync(babyId, cursor, limit, cancellationToken) switch
        {
            ListFeedsResult.Page page => Results.Ok(new FeedPageResponse(page.Entries.Select(ToResponse), page.Next)),
            ListFeedsResult.InvalidCursor => AuthEndpoints.ValidationProblem(new Dictionary<string, string> { ["cursor"] = "invalid" }),
            _ => BabyNotFound(),
        };

    private static async Task<IResult> BottleDefaultsAsync(Guid babyId, FeedService feeds, CancellationToken cancellationToken) =>
        await feeds.GetBottleDefaultsAsync(babyId, cancellationToken) is BottleDefaultsResult.Found { Defaults: var defaults }
            ? Results.Ok(new BottleDefaultsResponse(
                defaults.MilkType is { } milkType ? FeedFields.Format(milkType) : null,
                new LastAmountsResponse(defaults.LastBreastMilkMl, defaults.LastFormulaMl)))
            : BabyNotFound();

    /// <summary>201 when it created the in-progress breastfeed, 200 otherwise; 409 while another one is in progress (unless queued).</summary>
    private static async Task<IResult> StartSideAsync(
        Guid id, StartSideRequest request, FeedService feeds, HttpContext context, CancellationToken cancellationToken)
    {
        var missing = new Dictionary<string, string>();
        if (request.BabyId is null)
        {
            missing["babyId"] = "required";
        }

        if (request.SegmentId is null)
        {
            missing["segmentId"] = "required";
        }

        if (missing.Count > 0)
        {
            return AuthEndpoints.ValidationProblem(missing);
        }

        var result = await feeds.StartSideAsync(
            AuthEndpoints.CurrentUser(context)!, id, request.BabyId!.Value, request.SegmentId!.Value, request.Side, request.At,
            request.Queued ?? false, cancellationToken);
        return BreastfeedResponse(result);
    }

    private static async Task<IResult> StopSideAsync(
        Guid id, StopSideRequest request, FeedService feeds, HttpContext context, CancellationToken cancellationToken) =>
        BreastfeedResponse(await feeds.StopSideAsync(AuthEndpoints.CurrentUser(context)!, id, request.At, cancellationToken));

    private static async Task<IResult> FinishAsync(
        Guid id, FinishBreastfeedRequest request, FeedService feeds, HttpContext context, CancellationToken cancellationToken) =>
        BreastfeedResponse(await feeds.FinishAsync(
            AuthEndpoints.CurrentUser(context)!, id, new BreastfeedFinishInput(request.StartTime, request.Notes, request.At), cancellationToken));

    private static async Task<IResult> BreastfeedStateAsync(Guid babyId, FeedService feeds, CancellationToken cancellationToken) =>
        await feeds.GetBreastfeedStateAsync(babyId, cancellationToken) is BreastfeedStateResult.Found { State: var state }
            ? Results.Ok(new BreastfeedStateResponse(
                state.InProgress is { } inProgress ? ToResponse(inProgress) : null,
                state.LastSide is { } side ? FeedFields.Format(side) : null))
            : BabyNotFound();

    private static IResult BreastfeedResponse(BreastfeedResult result) => result switch
    {
        BreastfeedResult.Created created => Results.Created($"/api/feeds/{created.Entry.Feed.Id}", ToResponse(created.Entry)),
        BreastfeedResult.Updated updated => Results.Ok(ToResponse(updated.Entry)),
        BreastfeedResult.Invalid invalid => AuthEndpoints.ValidationProblem(invalid.Errors),
        BreastfeedResult.InProgressExists =>
            Results.Json(new ErrorResponse("breastfeedInProgress"), statusCode: StatusCodes.Status409Conflict),
        BreastfeedResult.BabyNotFound => BabyNotFound(),
        _ => FeedNotFound(),
    };

    private static IResult BabyNotFound() =>
        Results.Json(new ErrorResponse("babyNotFound"), statusCode: StatusCodes.Status404NotFound);

    private static IResult FeedNotFound() =>
        Results.Json(new ErrorResponse("feedNotFound"), statusCode: StatusCodes.Status404NotFound);

    private static FeedResponse ToResponse(FeedEntry entry)
    {
        var feed = entry.Feed;
        return new FeedResponse(
            feed.Id,
            feed.BabyId,
            FeedFields.Format(feed.Kind),
            feed.StartTime,
            feed.EndTime,
            feed.Notes,
            feed.MilkType is { } milkType ? FeedFields.Format(milkType) : null,
            feed.AmountMl,
            feed.MealType is { } mealType ? FeedFields.Format(mealType) : null,
            feed.Food,
            feed.Reaction is { } reaction ? FeedFields.Format(reaction) : null,
            feed.Segments.Select(s => new SegmentResponse(s.Id, FeedFields.Format(s.Side), s.StartedAt, s.EndedAt)),
            new UserNameResponse(entry.LoggedBy.Id, entry.LoggedBy.DisplayName),
            new UserNameResponse(entry.UpdatedBy.Id, entry.UpdatedBy.DisplayName),
            feed.CreatedAt,
            feed.UpdatedAt);
    }
}
