namespace Nala.Core.GrowthEntries;

/// <summary>The kinds of growth entry (spec 10).</summary>
public enum GrowthKind
{
    Measurement,
    Milestone,
}

/// <summary>A milestone's preset, or <see cref="Custom"/> with its own title (spec 10).</summary>
public enum GrowthMilestone
{
    FirstSmile,
    FirstLaugh,
    HoldsHead,
    RollsOver,
    SitsUp,
    Crawls,
    FirstTooth,
    StandsUp,
    FirstSteps,
    FirstWord,
    Custom,
}

/// <summary>
/// One growth entry of a baby (spec 10), dated with a calendar date, no time: a measurement (weight, length and head
/// circumference, each optional, at least one) or a milestone (a preset, or a custom one with its title). The fields of the
/// other kind are null. The id is generated by the client, so re-sending a queued entry is idempotent.
/// </summary>
public class GrowthEntry
{
    public Guid Id { get; init; }

    public Guid BabyId { get; init; }

    /// <summary>Never changes once created.</summary>
    public GrowthKind Kind { get; init; }

    /// <summary>A calendar date, no time or time zone; not before the baby's birth date.</summary>
    public DateOnly Date { get; set; }

    /// <summary>Whole grams, 300 to 30000; null when not given.</summary>
    public int? WeightG { get; set; }

    /// <summary>20 to 130, at most 1 decimal; null when not given.</summary>
    public decimal? LengthCm { get; set; }

    /// <summary>15 to 60, at most 1 decimal; null when not given.</summary>
    public decimal? HeadCircumferenceCm { get; set; }

    /// <summary>A milestone's preset or <see cref="GrowthMilestone.Custom"/>; null for a measurement.</summary>
    public GrowthMilestone? Milestone { get; set; }

    /// <summary>A custom milestone's title, 1 to 100 characters; null otherwise.</summary>
    public string? Title { get; set; }

    public string? Notes { get; set; }

    public Guid LoggedByUserId { get; init; }

    public DateTimeOffset CreatedAt { get; init; }

    public DateTimeOffset UpdatedAt { get; set; }

    public Guid UpdatedByUserId { get; set; }
}
