namespace Nala.Core.GrowthEntries;

/// <summary>The kinds of growth entry (spec 10); milestones come with slice 2.</summary>
public enum GrowthKind
{
    Measurement,
}

/// <summary>
/// One growth entry of a baby (spec 10): a measurement (weight, length and head circumference, each optional, at least one)
/// dated with a calendar date, no time. The id is generated by the client, so re-sending a queued entry is idempotent.
/// </summary>
public class GrowthEntry
{
    public Guid Id { get; init; }

    public Guid BabyId { get; init; }

    /// <summary>Never changes once created.</summary>
    public GrowthKind Kind { get; init; }

    /// <summary>A calendar date, no time or time zone; not before the baby's birth date.</summary>
    public DateOnly Date { get; set; }

    /// <summary>Whole grams, 300 to 30000; null when not given.</summary>
    public int? WeightG { get; set; }

    /// <summary>20 to 130, at most 1 decimal; null when not given.</summary>
    public decimal? LengthCm { get; set; }

    /// <summary>15 to 60, at most 1 decimal; null when not given.</summary>
    public decimal? HeadCircumferenceCm { get; set; }

    public string? Notes { get; set; }

    public Guid LoggedByUserId { get; init; }

    public DateTimeOffset CreatedAt { get; init; }

    public DateTimeOffset UpdatedAt { get; set; }

    public Guid UpdatedByUserId { get; set; }
}
