namespace Nala.Core.Diapers;

/// <summary>
/// One diaper change of a baby (spec 07): a time, wet / dirty toggles (neither is a dry diaper), a diaper-rash toggle and
/// notes. The id is generated by the client, so re-sending a queued diaper is idempotent.
/// </summary>
public class Diaper
{
    public Guid Id { get; init; }

    public Guid BabyId { get; init; }

    public DateTimeOffset Time { get; set; }

    public bool Wet { get; set; }

    public bool Dirty { get; set; }

    public bool Rash { get; set; }

    public string? Notes { get; set; }

    public Guid LoggedByUserId { get; init; }

    public DateTimeOffset CreatedAt { get; init; }

    public DateTimeOffset UpdatedAt { get; set; }

    public Guid UpdatedByUserId { get; set; }
}
